export const ALL_STATUSES = [
  "NEW",
  "ON HOLD",
  "DESIGNING",
  "DESIGNED",
  "NEED REPAIR",
  "REPAIRED",
  "CONFIRMED",
  "PROCESSING",
  "WAITING CUSTOMER",
  "SHIPPING",
  "EXPORTING",
  "WAIT IMAGE",
  "EMAILED",
  "TRACKING",
  "DELIVERED",
  "CANCELLED",
  "ADD PAYPAL",
  "WEB CHECKED",
  "WEB DONE",
  "DONE CHECK",
  "WEB",
  "NO TEMPLATE",
  "SEND MOCKUP",
  "MOCKUP SENT",
  "MOCKUP FAIL",
  "SEND IMAGE",
  "DONE IMAGE",
  "FAIL IMAGE",
  "WAIT SUPPORT",
  "FF PROCESS",
] as const

export type OrderStatus = (typeof ALL_STATUSES)[number] | (string & {})
